### ISSUE TITLE
Expired link to nv-codec-headers repo

### ISSUE THREAD

**Issue by NikolasEnt** [osai-ai/dokai#2]
Hi,
[git.videolan.org](https://git.videolan.org) is experiencing some issues again, it looks like the certificate for the domain is expired or something like that (but it was alive just a week ago!). Also, they are migrating to [code.videolan.org](https://code.videolan.org), however nv-codec-headers is not there yet.

The current link does not work:
https://github.com/osai-ai/dokai/blob/6f99608b70881de43740bc84c34f42249f4f65aa/docker/Dockerfile.base#L43

Temporary workaround:
`https://github.com/FFmpeg/nv-codec-headers.git`

**Comment by sankovalev** [comment]
Fixed in [dokai:22.03](https://github.com/osai-ai/dokai/tree/v22.03)
